### ISSUE TITLE
New deployment with the openfoodfacts spacename

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ubuntu#10]
Would it be possible to create an official version of the app within the Open Food Facts space name (something like org.openfoodfacts.scanner) with ownership of the account to contact@openfoodfacts.org ?
This is to ensure that we have all accounts (Android, iOS, Windows Phone and Ubuntu) within control the Open Food Facts association).

**Comment by sy-per** [comment]
If we can continue to Say our names, yes it is quite possible.

**Comment by sy-per** [comment]
The namespace can not be changed because I have other applications, and the namespace is contained in all applications
