### ISSUE TITLE
Add Travis support

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/openfoodfacts-ubuntu#11]
It allows to build and run test for each commit.

We already use it for the Android app and the python package. There's no official support but it seems easy to add
https://github.com/travis-ci/travis-ci/issues/2058

**Comment by Nymerea** [comment]
We don't have QML test for the application (unfortunattely)

**Comment by teolemon** [comment]
ok. let's leave that open for the glorious day we have time to test ;-)

**Comment by teolemon** [comment]
@Nymerea Is it possible to set it up and have it run with 0 tests for the moment ?

**Comment by Nymerea** [comment]
I can write it, but I don't know how to lunch it ! I've to learn the good way to test an application with qml
