### ISSUE TITLE
no focus since few months

### ISSUE THREAD

**Issue by vinber** [openfoodfacts/openfoodfacts-ubuntu#5]
Hello, i use openfoodfact for ubuntuphone on bq aquaris 5. Since few months there is no focus so i can use it. Have you any idea to solve this ?
Thanks for this application!

**Comment by Nymerea** [comment]
Hello,

I'll look into it tomorrow, I'll tell what i've found !

**Comment by vinber** [comment]
Thank you. If i can help you, tell me of course

**Comment by vinber** [comment]
Sorry but do you find something ?

**Comment by Nymerea** [comment]
Hello, bugfix has been commited ! Just wait the publication on the store :-)

**Comment by vinber** [comment]
thanks a lot

**Comment by Nymerea** [comment]
did update fix the issue ?

**Comment by vinber** [comment]
partially, focus is ok now but there no recognition of the bar code, so no links to the app

**Comment by Nymerea** [comment]
Sorry, I don't understand the issue.

Now, you can zoom, so you have to place the barcode to the rectangle, and wait the focus. Normally it should work.

Is the issue elsewhere ?

**Comment by vinber** [comment]
I tried again and now it's ok if i use phone verticaly.
And on same product if i use horizontaly it doesn't work (focus ok but it doesn't recognize product : i suppose i make my first test horizontally ?).

**Comment by vinber** [comment]
I open new issue #12
